#Every time there is an update on main, server pulls on auto.
name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - run: |
          cd ~/recip
          git pull origin main
          docker compose build
          docker compose --profile production up -d
