#Every time there is an update on main, server pulls on auto.
name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - run: |
          cd ~/recip
          docker-compose down
          git pull origin main
          docker-compose up -d --build
